services:
  server:
    container_name: server
    build:
      dockerfile: "Dockerfile.sr"
    restart: always
    environment:
      - PORT=6379
    ports: [8080:8080]
    depends_on:
    - db
    - client

  db:
    container_name: redis
    image: redis:latest
    restart: always
    ports: [6379:6379]

  client:
    container_name: client
    build:
      dockerfile: "Dockerfile.cl"
    restart: always
    ports: [3030:3030]